spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/galaxy
    username: admin
    password: 123
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    open-in-view: true

server:
  error:
    include-stacktrace: never
    include-message: never
