spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/galaxy
    username: admin
    password: 123
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  error:
    include-stacktrace: never
    include-message: never
